---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 766442499678273537-sJiIHoa1TpiZpbGRCs6JHjmtJXoknlI
:access_token_secret: rbtOK2fwsXxaLO5ifr9MY8wmlIKqp0q1Yf0wpJsAqupTD
